// eslint-disable-next-line import/prefer-default-export
export const constants = [
  { number: 1, txt: 'one' },
  { number: 2, txt: 'two' },
  { number: 3, txt: 'three' },
  { number: 4, txt: 'four' },
  { number: 5, txt: 'five' },
  { number: 6, txt: 'six' },
  { number: 7, txt: 'seven' },
  { number: 8, txt: 'eight' },
  { number: 9, txt: 'nine' },
  { number: 10, txt: 'ten' },
  { number: 11, txt: 'eleven' },
  { number: 12, txt: 'twelve' },
  { number: 13, txt: 'thirteen' },
  { number: 14, txt: 'fourteen' },
  { number: 15, txt: 'fifteen' },
  { number: 16, txt: 'sixteen' },
  { number: 17, txt: 'seventeen' },
  { number: 18, txt: 'eighteen' },
  { number: 19, txt: 'nineteen' },
  { number: 20, txt: 'twenty' },
  { number: 30, txt: 'thirty' },
  { number: 40, txt: 'fourty' },
  { number: 50, txt: 'fifty' },
  { number: 60, txt: 'sixty' },
  { number: 70, txt: 'seventy' },
  { number: 80, txt: 'eighty' },
  { number: 90, txt: 'ningty' },
  { number: 100, txt: 'houndred' },
  { number: 1000, txt: 'thousand' },
  { number: 1000000, txt: 'million' },
  { number: 1000000000, txt: 'billion' },
];
